name: David Peterson
description: A Sitecore Development and Research Blog
meta_description: "A Sitecore Development and Research Blog"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://petersondave.com'
author:         'David Peterson'

kramdown:
    input: GFM